import type { Metadata } from 'next';

/*
 * Keeping Server-only Code out of the Client Environment
 *  https://nextjs.org/docs/app/building-your-application/rendering/composition-patterns#keeping-server-only-code-out-of-the-client-environment
 */
import 'server-only';

import CustomThemeProvider from '~/providers/CustomThemeProvider';
import { notoSans } from '~/styles/theme';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko">
      <body className={notoSans.className}>
        <CustomThemeProvider>{children}</CustomThemeProvider>
      </body>
    </html>
  );
}
