import type { Metadata } from 'next';
import { Noto_Sans } from 'next/font/google';

import CustomThemeProvider from '~/providers/customThemeProvider';

const notoSans = Noto_Sans({
  weight: ['400', '700'],
  subsets: ['latin'],
  preload: true,
  adjustFontFallback: true,
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko">
      <body className={notoSans.className}>
        <CustomThemeProvider>{children}</CustomThemeProvider>
      </body>
    </html>
  );
}
